[build-system]
requires = ["setuptools>=65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["Backend", "pdf_interpretation"]
include = ["*", "*.*"]

[project.scripts]
app = "Backend.main:app"
